language: node_js

node_js:
    - "6.9.1"

env:
    global:
        - CXX=g++-4.8
        - NODE_ENV=test
        - CHROME_BIN="chromium-browser"
        - DISPLAY=:99.0

dist: trusty
sudo: required

addons:
    postgresql: "9.3"
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

services:
    - postgresql

cache:
    directories:
        - node_modules

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - cp ./config/test-dist.js ./config/test.js

before_install:
    - sh -e /etc/init.d/xvfb start
    - sleep 3

install:
    - "make --silent install"
